<table width="100%"> <tr>
        <td  style="background-color:#ffffff;">
            <a href="https://qsoftware.lu.lv/index.php/qworld/" target="_blank"><img src="..\images\qworld.jpg" width="35%" align="left"> </a></td>
        <td style="background-color:#ffffff;vertical-align:bottom;text-align:right;">
            prepared by Abuzer Yakaryilmaz (<a href="http://qworld.lu.lv/index.php/qlatvia/" target="_blank">QLatvia</a>)
        </td>        
</tr></table>

<table width="100%"><tr><td style="color:#bbbbbb;background-color:#ffffff;font-size:11px;font-style:italic;text-align:right;">This cell contains some macros. If there is a problem with displaying mathematical formulas, please run this cell to load these macros. </td></tr></table>
$ \newcommand{\bra}[1]{\langle #1|} $
$ \newcommand{\ket}[1]{|#1\rangle} $
$ \newcommand{\braket}[2]{\langle #1|#2\rangle} $
$ \newcommand{\dot}[2]{ #1 \cdot #2} $
$ \newcommand{\biginner}[2]{\left\langle #1,#2\right\rangle} $
$ \newcommand{\mymatrix}[2]{\left( \begin{array}{#1} #2\end{array} \right)} $
$ \newcommand{\myvector}[1]{\mymatrix{c}{#1}} $
$ \newcommand{\myrvector}[1]{\mymatrix{r}{#1}} $
$ \newcommand{\mypar}[1]{\left( #1 \right)} $
$ \newcommand{\mybigpar}[1]{ \Big( #1 \Big)} $
$ \newcommand{\sqrttwo}{\frac{1}{\sqrt{2}}} $
$ \newcommand{\dsqrttwo}{\dfrac{1}{\sqrt{2}}} $
$ \newcommand{\onehalf}{\frac{1}{2}} $
$ \newcommand{\donehalf}{\dfrac{1}{2}} $
$ \newcommand{\hadamard}{ \mymatrix{rr}{ \sqrttwo & \sqrttwo \\ \sqrttwo & -\sqrttwo }} $
$ \newcommand{\vzero}{\myvector{1\\0}} $
$ \newcommand{\vone}{\myvector{0\\1}} $
$ \newcommand{\vhadamardzero}{\myvector{ \sqrttwo \\  \sqrttwo } } $
$ \newcommand{\vhadamardone}{ \myrvector{ \sqrttwo \\ -\sqrttwo } } $
$ \newcommand{\myarray}[2]{ \begin{array}{#1}#2\end{array}} $
$ \newcommand{\X}{ \mymatrix{cc}{0 & 1 \\ 1 & 0}  } $
$ \newcommand{\Z}{ \mymatrix{rr}{1 & 0 \\ 0 & -1}  } $
$ \newcommand{\Htwo}{ \mymatrix{rrrr}{ \frac{1}{2} & \frac{1}{2} & \frac{1}{2} & \frac{1}{2} \\ \frac{1}{2} & -\frac{1}{2} & \frac{1}{2} & -\frac{1}{2} \\ \frac{1}{2} & \frac{1}{2} & -\frac{1}{2} & -\frac{1}{2} \\ \frac{1}{2} & -\frac{1}{2} & -\frac{1}{2} & \frac{1}{2} } } $
$ \newcommand{\CNOT}{ \mymatrix{cccc}{1 & 0 & 0 & 0 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 0 & 1 \\ 0 & 0 & 1 & 0} } $
$ \newcommand{\norm}[1]{ \left\lVert #1 \right\rVert } $

<h2> Coin Flip: A Probabilistic Bit </h2>

[Watch Lecture](https://youtu.be/uGKHEsVcSEs)

<h3> A fair coin </h3>

A coin has two sides: <i>Head</i> and <i>Tail</i>.

After flipping a coin, we can get a Head or a Tail. We can represent these two cases by a single bit:
<ul>
    <li> 0 represents Head </li>
    <li> 1 represents Tail </li>
</ul>

<h3> Flipping a fair coin </h3>

If our coin is fair, then the probabilities of getting a Head and a Tail are equal:

$ p= \dfrac{1}{2} = 0.5 $.

Flipping a fair coin can be represented as an operator:
<ul>
    <li> $ FairCoin(Head) = \frac{1}{2} Head + \frac{1}{2}Tail $ </li>
    <li> $ FairCoin(Tail) = \frac{1}{2} Head + \frac{1}{2}Tail $ </li>
</ul>
$
FairCoin = \begin{array}{c|cc} & \mathbf{Head} & \mathbf{Tail} \\ \hline \mathbf{Head} & \dfrac{1}{2} & \dfrac{1}{2} \\  \mathbf{Tail} & \dfrac{1}{2} & \dfrac{1}{2}  \end{array}
$

Or, by using 0 and 1:

$
FairCoin = \begin{array}{c|cc} & \mathbf{0} & \mathbf{1} \\ \hline \mathbf{0} & \dfrac{1}{2} & \dfrac{1}{2} \\  \mathbf{1} & \dfrac{1}{2} & \dfrac{1}{2}  \end{array}
$

<h3> Task 1: Simulating FairCoin in Python</h3>

Flip a fair coin 100 times. Calculate the total number of heads and tails, and then check the ratio of the number of heads and the number of tails.

Do the same experiment 1000 times.

Do the same experiment 10,000 times.

Do the same experiment 100,000 times.

Do your results get close to the ideal case (the numbers of heads and tails are equal)?

In [18]:
from random import randrange
import numpy as np
#
# you may use method 'randrange' for this task
# randrange(n) return a value from {0,1,...,n-1} randomly
#

#
# your solution is here
#
def coin_fair(lim):
    i = 0
    h_t = np.zeros([2, 1])
    
    for i in range(lim):
        x = randrange(2)
        h_t[x] +=1
    return h_t


lim = 100

j = 0
for j in range(4):
    head_tails = coin_fair(lim)
    print("For ", lim, " flips: ")
    print(head_tails)
    print("Ratio: ")
    print(head_tails/lim)
    lim = lim * 10

For  100  flips: 
[[49.]
 [51.]]
Ratio: 
[[0.49]
 [0.51]]
For  1000  flips: 
[[475.]
 [525.]]
Ratio: 
[[0.475]
 [0.525]]
For  10000  flips: 
[[4952.]
 [5048.]]
Ratio: 
[[0.4952]
 [0.5048]]
For  100000  flips: 
[[49897.]
 [50103.]]
Ratio: 
[[0.49897]
 [0.50103]]


<a href="B06_Coin_Flip_Solutions.ipynb#task1">click for our solution</a>

<h3> Flipping a biased coin </h3>

Our coin may have a bias. 

For example, the probability of getting head is greater than the probability of getting tail.

Here is an example:

$
BiasedCoin = \begin{array}{c|cc} & \mathbf{Head} & \mathbf{Tail} \\ \hline \mathbf{Head} & 0.6 & 0.6 \\  \mathbf{Tail} & 0.4 & 0.4  \end{array}
$

Or, by using 0 and 1 as the states:

$
BiasedCoin = \begin{array}{c|cc} & \mathbf{0} & \mathbf{1} \\ \hline \mathbf{0} & 0.6 & 0.6\\  \mathbf{1} & 0.4 & 0.4 \end{array}
$

<h3> Task 2: Simulating BiasedCoin in Python</h3>

Flip the following biased coin 100 times. Calculate the total numbers of heads and tails, and then check the ratio of the number of heads and the number of tails.

$
BiasedCoin = \begin{array}{c|cc} & \mathbf{Head} & \mathbf{Tail} \\ \hline \mathbf{Head} & 0.6 & 0.6 \\  \mathbf{Tail} & 0.4 & 0.4  \end{array}
$


Do the same experiment 1000 times.

Do the same experiment 10,000 times.

Do the same experiment 100,000 times.

Do your results get close to the ideal case $ \mypar{ \dfrac{ \mbox{# of heads} }{ \mbox{# of tails} } = \dfrac{0.6}{0.4} = 1.50000000 } $?

In [20]:
#
# you may use method 'randrange' for this task
# randrange(n) return a value from {0,1,...,n-1} randomly
#

#
# your solution is here
#
def coin_unfair(lim):
    i = 0
    h_t = np.zeros([2, 1])
    
    for i in range(lim):
        x = randrange(10)
        if x <= 5:
            h_t[0] +=1
        else:
            h_t[1] +=1
    return h_t


lim = 100

j = 0
for j in range(4):
    head_tails = coin_unfair(lim)
    print("For ", lim, " flips: ")
    print(head_tails)
    print("Ratio: ")
    print(head_tails/lim)
    lim = lim * 10

For  100  flips: 
[[64.]
 [36.]]
Ratio: 
[[0.64]
 [0.36]]
For  1000  flips: 
[[600.]
 [400.]]
Ratio: 
[[0.6]
 [0.4]]
For  10000  flips: 
[[6003.]
 [3997.]]
Ratio: 
[[0.6003]
 [0.3997]]
For  100000  flips: 
[[59884.]
 [40116.]]
Ratio: 
[[0.59884]
 [0.40116]]


<a href="B06_Coin_Flip_Solutions.ipynb#task2">click for our solution</a>

<h3> Programming a biased coin [extra] </h3>

We use a simple method to create a biased coin.

First, we pick a range for the precision of probabilities, say $ N $, as $ N = 11, 101, 1001, \mbox{ or }, 10^k+1 $ for some $ k > 4 $.

Second, we pick the bias, say $ B $, as an integer between 0 and $ N $.

We fix $ N $ and $ B $.

Third, we pick a random integer between 0 and $ N $:
<ul>
    <li> if it is less than $ B $, we say "Head" and </li>
    <li> if it is equal to $ B $ or greater than $ B $, we say "Tail" </li>
</ul>
    
In this way, we can have a biased coin "landing" head with probability $ \frac{B}{N} $.

Remark that we pick $ N = 10^k+1 $. In this way, the coin cannot be fair if $ B $ is an integer. ($ \frac{10^k+1}{2} $ is not an integer.)

<h3> Task 3 </h3>

Write a function to implement the described biased coin,

The inputs are integers $ N >0 $ and $ 0 \leq B < N $.

The output is either "Head" or "Tail".

In [21]:
def biased_coin(N,B):
    from random import randrange
    #
    # your solution is here
    #
    x = randrange(N)
    if x < B:
        return "Head"
    else:
        return "Tail"

<a href="B06_Coin_Flip_Solutions.ipynb#task3">click for our solution</a>

<h3> Task 4</h3>

We use the biased coin defined in Task 3. 

(You may use the one given in the solution.)

We pick $ N $ as 101.

We determine $ B $ randomly, and we do not check its value immediately.

The task is to guess the bias by using the biased coin at most 500 times.

Check the real bias, and calculate the error.

In [36]:
from random import randrange
N = 101
B = randrange(100)
#
# your solution is here
#
i = 0
h_t = np.zeros([2, 1])
lim = 500 

for i in range(lim):
    x = biased_coin(N,B)
    if x == "Head":
        h_t[0] +=1
    else:
        h_t[1] +=1
        
print("Flips: ")
print(h_t)
print("Ratio: ")
print(h_t/lim)

h_prob = h_t[0] / lim
B_guess = N * h_prob

print("Guess for B: ", B_guess)
print("Actual B: ", B)

error = ((B - B_guess) / B) * 100
print("Error: ", error, "%")

Flips: 
[[428.]
 [ 72.]]
Ratio: 
[[0.856]
 [0.144]]
Guess for B:  [86.456]
Actual B:  89
Error:  [2.85842697] %


<a href="B06_Coin_Flip_Solutions.ipynb#task4">click for our solution</a>